language: php

php:
  - 7.3.1

before_script:
  - cp .env.travis .env
  - mysql -e 'create database homestead_test;'
  - composer self-update
  - composer install --no-interaction
  - php srtisan generate:key

script:
  - vendor/bin/phpunit


deploy:
  provider: pages
  github_token: e5370e7aa4633def2fb402a227e8bfe4355f5808
  on:
     branch: master



